# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28466a7118003ef5967b225ae05f5b4b948e137c21309f2c57b1c3733290a82ca3c3010a081ca55ffffcc88a6f9420da12a999e1de09e37568594879076f28f3

test:
  secret_key_base: 27b8773425108ceb0905a8739dd8a3d4f2f92da118d2e4646c37569aa30446dd3325a78ee46e6f4b5e2657ed39fd35319b801d808dbf6e1ddf55b30a9c350d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
